import Head from "next/head";
import { useState, useEffect } from "react";
import { cardsData } from "../data";
import { AnimatePresence } from "framer-motion";
import Card from "../components/Card";

export default function Home() {
  const [cards, setCards] = useState([]);
  const [selectedCards, setSelectedCards] = useState([]);

  useEffect(() => {
    setCards(cardsData);
  }, []);

  const onClickHandler = (card) => {
    if (selectedCards.includes(card)) return;
    setSelectedCards([...selectedCards, card]);
  };

  return (
    <div className='h-screen min-h-screen bg-neutral-800'>
      <Head>
        <title>multiple cards</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='h-full flex'>
        <aside className='bg-slate-300 h-full w-[200px]'>
          <ul className='p-4 flex flex-col space-y-4 font-semibold mt-10'>
            {cards?.map((card) => {
              return (
                <li
                  onClick={() => onClickHandler(card)}
                  className='cursor-pointer'
                  key={card.id}
                >
                  {card.title}
                </li>
              );
            })}
          </ul>
        </aside>
        <section className='flex-grow text-white relative overflow-hidden'>
          <AnimatePresence>
            {selectedCards.map((card, index) => {
              return (
                <Card
                  key={card.id}
                  index={index}
                  setSelectedCards={setSelectedCards}
                  selectedCards={selectedCards}
                  card={card}
                />
              );
            })}
          </AnimatePresence>
        </section>
      </main>
    </div>
  );
}
